//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace client.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Generating message contract since element name Name from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Add", ReplyAction="*")]
        client.ServiceReference1.AddResponse Add(client.ServiceReference1.AddRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Add", ReplyAction="*")]
        System.Threading.Tasks.Task<client.ServiceReference1.AddResponse> AddAsync(client.ServiceReference1.AddRequest request);
        
        // CODEGEN: Generating message contract since element name Name from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Delete", ReplyAction="*")]
        client.ServiceReference1.DeleteResponse Delete(client.ServiceReference1.DeleteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Delete", ReplyAction="*")]
        System.Threading.Tasks.Task<client.ServiceReference1.DeleteResponse> DeleteAsync(client.ServiceReference1.DeleteRequest request);
        
        // CODEGEN: Generating message contract since element name Name from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ModifyDescription", ReplyAction="*")]
        client.ServiceReference1.ModifyDescriptionResponse ModifyDescription(client.ServiceReference1.ModifyDescriptionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ModifyDescription", ReplyAction="*")]
        System.Threading.Tasks.Task<client.ServiceReference1.ModifyDescriptionResponse> ModifyDescriptionAsync(client.ServiceReference1.ModifyDescriptionRequest request);
        
        // CODEGEN: Generating message contract since element name Name from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ModifyPlayers", ReplyAction="*")]
        client.ServiceReference1.ModifyPlayersResponse ModifyPlayers(client.ServiceReference1.ModifyPlayersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ModifyPlayers", ReplyAction="*")]
        System.Threading.Tasks.Task<client.ServiceReference1.ModifyPlayersResponse> ModifyPlayersAsync(client.ServiceReference1.ModifyPlayersRequest request);
        
        // CODEGEN: Generating message contract since element name Name from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ModifyTrophies", ReplyAction="*")]
        client.ServiceReference1.ModifyTrophiesResponse ModifyTrophies(client.ServiceReference1.ModifyTrophiesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ModifyTrophies", ReplyAction="*")]
        System.Threading.Tasks.Task<client.ServiceReference1.ModifyTrophiesResponse> ModifyTrophiesAsync(client.ServiceReference1.ModifyTrophiesRequest request);
        
        // CODEGEN: Generating message contract since element name Name from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ModifyValue", ReplyAction="*")]
        client.ServiceReference1.ModifyValueResponse ModifyValue(client.ServiceReference1.ModifyValueRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ModifyValue", ReplyAction="*")]
        System.Threading.Tasks.Task<client.ServiceReference1.ModifyValueResponse> ModifyValueAsync(client.ServiceReference1.ModifyValueRequest request);
        
        // CODEGEN: Generating message contract since element name GetElementsResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetElements", ReplyAction="*")]
        client.ServiceReference1.GetElementsResponse GetElements(client.ServiceReference1.GetElementsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetElements", ReplyAction="*")]
        System.Threading.Tasks.Task<client.ServiceReference1.GetElementsResponse> GetElementsAsync(client.ServiceReference1.GetElementsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Add", Namespace="http://tempuri.org/", Order=0)]
        public client.ServiceReference1.AddRequestBody Body;
        
        public AddRequest() {
        }
        
        public AddRequest(client.ServiceReference1.AddRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Description;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int Players;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int Trophies;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public long Value;
        
        public AddRequestBody() {
        }
        
        public AddRequestBody(string Name, string Description, int Players, int Trophies, long Value) {
            this.Name = Name;
            this.Description = Description;
            this.Players = Players;
            this.Trophies = Trophies;
            this.Value = Value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddResponse", Namespace="http://tempuri.org/", Order=0)]
        public client.ServiceReference1.AddResponseBody Body;
        
        public AddResponse() {
        }
        
        public AddResponse(client.ServiceReference1.AddResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class AddResponseBody {
        
        public AddResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Delete", Namespace="http://tempuri.org/", Order=0)]
        public client.ServiceReference1.DeleteRequestBody Body;
        
        public DeleteRequest() {
        }
        
        public DeleteRequest(client.ServiceReference1.DeleteRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Name;
        
        public DeleteRequestBody() {
        }
        
        public DeleteRequestBody(string Name) {
            this.Name = Name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteResponse", Namespace="http://tempuri.org/", Order=0)]
        public client.ServiceReference1.DeleteResponseBody Body;
        
        public DeleteResponse() {
        }
        
        public DeleteResponse(client.ServiceReference1.DeleteResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class DeleteResponseBody {
        
        public DeleteResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ModifyDescriptionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ModifyDescription", Namespace="http://tempuri.org/", Order=0)]
        public client.ServiceReference1.ModifyDescriptionRequestBody Body;
        
        public ModifyDescriptionRequest() {
        }
        
        public ModifyDescriptionRequest(client.ServiceReference1.ModifyDescriptionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ModifyDescriptionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Description;
        
        public ModifyDescriptionRequestBody() {
        }
        
        public ModifyDescriptionRequestBody(string Name, string Description) {
            this.Name = Name;
            this.Description = Description;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ModifyDescriptionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ModifyDescriptionResponse", Namespace="http://tempuri.org/", Order=0)]
        public client.ServiceReference1.ModifyDescriptionResponseBody Body;
        
        public ModifyDescriptionResponse() {
        }
        
        public ModifyDescriptionResponse(client.ServiceReference1.ModifyDescriptionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ModifyDescriptionResponseBody {
        
        public ModifyDescriptionResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ModifyPlayersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ModifyPlayers", Namespace="http://tempuri.org/", Order=0)]
        public client.ServiceReference1.ModifyPlayersRequestBody Body;
        
        public ModifyPlayersRequest() {
        }
        
        public ModifyPlayersRequest(client.ServiceReference1.ModifyPlayersRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ModifyPlayersRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Name;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int Players;
        
        public ModifyPlayersRequestBody() {
        }
        
        public ModifyPlayersRequestBody(string Name, int Players) {
            this.Name = Name;
            this.Players = Players;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ModifyPlayersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ModifyPlayersResponse", Namespace="http://tempuri.org/", Order=0)]
        public client.ServiceReference1.ModifyPlayersResponseBody Body;
        
        public ModifyPlayersResponse() {
        }
        
        public ModifyPlayersResponse(client.ServiceReference1.ModifyPlayersResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ModifyPlayersResponseBody {
        
        public ModifyPlayersResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ModifyTrophiesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ModifyTrophies", Namespace="http://tempuri.org/", Order=0)]
        public client.ServiceReference1.ModifyTrophiesRequestBody Body;
        
        public ModifyTrophiesRequest() {
        }
        
        public ModifyTrophiesRequest(client.ServiceReference1.ModifyTrophiesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ModifyTrophiesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Name;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int Trophies;
        
        public ModifyTrophiesRequestBody() {
        }
        
        public ModifyTrophiesRequestBody(string Name, int Trophies) {
            this.Name = Name;
            this.Trophies = Trophies;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ModifyTrophiesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ModifyTrophiesResponse", Namespace="http://tempuri.org/", Order=0)]
        public client.ServiceReference1.ModifyTrophiesResponseBody Body;
        
        public ModifyTrophiesResponse() {
        }
        
        public ModifyTrophiesResponse(client.ServiceReference1.ModifyTrophiesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ModifyTrophiesResponseBody {
        
        public ModifyTrophiesResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ModifyValueRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ModifyValue", Namespace="http://tempuri.org/", Order=0)]
        public client.ServiceReference1.ModifyValueRequestBody Body;
        
        public ModifyValueRequest() {
        }
        
        public ModifyValueRequest(client.ServiceReference1.ModifyValueRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ModifyValueRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Name;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public long Value;
        
        public ModifyValueRequestBody() {
        }
        
        public ModifyValueRequestBody(string Name, long Value) {
            this.Name = Name;
            this.Value = Value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ModifyValueResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ModifyValueResponse", Namespace="http://tempuri.org/", Order=0)]
        public client.ServiceReference1.ModifyValueResponseBody Body;
        
        public ModifyValueResponse() {
        }
        
        public ModifyValueResponse(client.ServiceReference1.ModifyValueResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ModifyValueResponseBody {
        
        public ModifyValueResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetElementsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetElements", Namespace="http://tempuri.org/", Order=0)]
        public client.ServiceReference1.GetElementsRequestBody Body;
        
        public GetElementsRequest() {
        }
        
        public GetElementsRequest(client.ServiceReference1.GetElementsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetElementsRequestBody {
        
        public GetElementsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetElementsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetElementsResponse", Namespace="http://tempuri.org/", Order=0)]
        public client.ServiceReference1.GetElementsResponseBody Body;
        
        public GetElementsResponse() {
        }
        
        public GetElementsResponse(client.ServiceReference1.GetElementsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetElementsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public client.ServiceReference1.ArrayOfString GetElementsResult;
        
        public GetElementsResponseBody() {
        }
        
        public GetElementsResponseBody(client.ServiceReference1.ArrayOfString GetElementsResult) {
            this.GetElementsResult = GetElementsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : client.ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<client.ServiceReference1.WebService1Soap>, client.ServiceReference1.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        client.ServiceReference1.AddResponse client.ServiceReference1.WebService1Soap.Add(client.ServiceReference1.AddRequest request) {
            return base.Channel.Add(request);
        }
        
        public void Add(string Name, string Description, int Players, int Trophies, long Value) {
            client.ServiceReference1.AddRequest inValue = new client.ServiceReference1.AddRequest();
            inValue.Body = new client.ServiceReference1.AddRequestBody();
            inValue.Body.Name = Name;
            inValue.Body.Description = Description;
            inValue.Body.Players = Players;
            inValue.Body.Trophies = Trophies;
            inValue.Body.Value = Value;
            client.ServiceReference1.AddResponse retVal = ((client.ServiceReference1.WebService1Soap)(this)).Add(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<client.ServiceReference1.AddResponse> client.ServiceReference1.WebService1Soap.AddAsync(client.ServiceReference1.AddRequest request) {
            return base.Channel.AddAsync(request);
        }
        
        public System.Threading.Tasks.Task<client.ServiceReference1.AddResponse> AddAsync(string Name, string Description, int Players, int Trophies, long Value) {
            client.ServiceReference1.AddRequest inValue = new client.ServiceReference1.AddRequest();
            inValue.Body = new client.ServiceReference1.AddRequestBody();
            inValue.Body.Name = Name;
            inValue.Body.Description = Description;
            inValue.Body.Players = Players;
            inValue.Body.Trophies = Trophies;
            inValue.Body.Value = Value;
            return ((client.ServiceReference1.WebService1Soap)(this)).AddAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        client.ServiceReference1.DeleteResponse client.ServiceReference1.WebService1Soap.Delete(client.ServiceReference1.DeleteRequest request) {
            return base.Channel.Delete(request);
        }
        
        public void Delete(string Name) {
            client.ServiceReference1.DeleteRequest inValue = new client.ServiceReference1.DeleteRequest();
            inValue.Body = new client.ServiceReference1.DeleteRequestBody();
            inValue.Body.Name = Name;
            client.ServiceReference1.DeleteResponse retVal = ((client.ServiceReference1.WebService1Soap)(this)).Delete(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<client.ServiceReference1.DeleteResponse> client.ServiceReference1.WebService1Soap.DeleteAsync(client.ServiceReference1.DeleteRequest request) {
            return base.Channel.DeleteAsync(request);
        }
        
        public System.Threading.Tasks.Task<client.ServiceReference1.DeleteResponse> DeleteAsync(string Name) {
            client.ServiceReference1.DeleteRequest inValue = new client.ServiceReference1.DeleteRequest();
            inValue.Body = new client.ServiceReference1.DeleteRequestBody();
            inValue.Body.Name = Name;
            return ((client.ServiceReference1.WebService1Soap)(this)).DeleteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        client.ServiceReference1.ModifyDescriptionResponse client.ServiceReference1.WebService1Soap.ModifyDescription(client.ServiceReference1.ModifyDescriptionRequest request) {
            return base.Channel.ModifyDescription(request);
        }
        
        public void ModifyDescription(string Name, string Description) {
            client.ServiceReference1.ModifyDescriptionRequest inValue = new client.ServiceReference1.ModifyDescriptionRequest();
            inValue.Body = new client.ServiceReference1.ModifyDescriptionRequestBody();
            inValue.Body.Name = Name;
            inValue.Body.Description = Description;
            client.ServiceReference1.ModifyDescriptionResponse retVal = ((client.ServiceReference1.WebService1Soap)(this)).ModifyDescription(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<client.ServiceReference1.ModifyDescriptionResponse> client.ServiceReference1.WebService1Soap.ModifyDescriptionAsync(client.ServiceReference1.ModifyDescriptionRequest request) {
            return base.Channel.ModifyDescriptionAsync(request);
        }
        
        public System.Threading.Tasks.Task<client.ServiceReference1.ModifyDescriptionResponse> ModifyDescriptionAsync(string Name, string Description) {
            client.ServiceReference1.ModifyDescriptionRequest inValue = new client.ServiceReference1.ModifyDescriptionRequest();
            inValue.Body = new client.ServiceReference1.ModifyDescriptionRequestBody();
            inValue.Body.Name = Name;
            inValue.Body.Description = Description;
            return ((client.ServiceReference1.WebService1Soap)(this)).ModifyDescriptionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        client.ServiceReference1.ModifyPlayersResponse client.ServiceReference1.WebService1Soap.ModifyPlayers(client.ServiceReference1.ModifyPlayersRequest request) {
            return base.Channel.ModifyPlayers(request);
        }
        
        public void ModifyPlayers(string Name, int Players) {
            client.ServiceReference1.ModifyPlayersRequest inValue = new client.ServiceReference1.ModifyPlayersRequest();
            inValue.Body = new client.ServiceReference1.ModifyPlayersRequestBody();
            inValue.Body.Name = Name;
            inValue.Body.Players = Players;
            client.ServiceReference1.ModifyPlayersResponse retVal = ((client.ServiceReference1.WebService1Soap)(this)).ModifyPlayers(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<client.ServiceReference1.ModifyPlayersResponse> client.ServiceReference1.WebService1Soap.ModifyPlayersAsync(client.ServiceReference1.ModifyPlayersRequest request) {
            return base.Channel.ModifyPlayersAsync(request);
        }
        
        public System.Threading.Tasks.Task<client.ServiceReference1.ModifyPlayersResponse> ModifyPlayersAsync(string Name, int Players) {
            client.ServiceReference1.ModifyPlayersRequest inValue = new client.ServiceReference1.ModifyPlayersRequest();
            inValue.Body = new client.ServiceReference1.ModifyPlayersRequestBody();
            inValue.Body.Name = Name;
            inValue.Body.Players = Players;
            return ((client.ServiceReference1.WebService1Soap)(this)).ModifyPlayersAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        client.ServiceReference1.ModifyTrophiesResponse client.ServiceReference1.WebService1Soap.ModifyTrophies(client.ServiceReference1.ModifyTrophiesRequest request) {
            return base.Channel.ModifyTrophies(request);
        }
        
        public void ModifyTrophies(string Name, int Trophies) {
            client.ServiceReference1.ModifyTrophiesRequest inValue = new client.ServiceReference1.ModifyTrophiesRequest();
            inValue.Body = new client.ServiceReference1.ModifyTrophiesRequestBody();
            inValue.Body.Name = Name;
            inValue.Body.Trophies = Trophies;
            client.ServiceReference1.ModifyTrophiesResponse retVal = ((client.ServiceReference1.WebService1Soap)(this)).ModifyTrophies(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<client.ServiceReference1.ModifyTrophiesResponse> client.ServiceReference1.WebService1Soap.ModifyTrophiesAsync(client.ServiceReference1.ModifyTrophiesRequest request) {
            return base.Channel.ModifyTrophiesAsync(request);
        }
        
        public System.Threading.Tasks.Task<client.ServiceReference1.ModifyTrophiesResponse> ModifyTrophiesAsync(string Name, int Trophies) {
            client.ServiceReference1.ModifyTrophiesRequest inValue = new client.ServiceReference1.ModifyTrophiesRequest();
            inValue.Body = new client.ServiceReference1.ModifyTrophiesRequestBody();
            inValue.Body.Name = Name;
            inValue.Body.Trophies = Trophies;
            return ((client.ServiceReference1.WebService1Soap)(this)).ModifyTrophiesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        client.ServiceReference1.ModifyValueResponse client.ServiceReference1.WebService1Soap.ModifyValue(client.ServiceReference1.ModifyValueRequest request) {
            return base.Channel.ModifyValue(request);
        }
        
        public void ModifyValue(string Name, long Value) {
            client.ServiceReference1.ModifyValueRequest inValue = new client.ServiceReference1.ModifyValueRequest();
            inValue.Body = new client.ServiceReference1.ModifyValueRequestBody();
            inValue.Body.Name = Name;
            inValue.Body.Value = Value;
            client.ServiceReference1.ModifyValueResponse retVal = ((client.ServiceReference1.WebService1Soap)(this)).ModifyValue(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<client.ServiceReference1.ModifyValueResponse> client.ServiceReference1.WebService1Soap.ModifyValueAsync(client.ServiceReference1.ModifyValueRequest request) {
            return base.Channel.ModifyValueAsync(request);
        }
        
        public System.Threading.Tasks.Task<client.ServiceReference1.ModifyValueResponse> ModifyValueAsync(string Name, long Value) {
            client.ServiceReference1.ModifyValueRequest inValue = new client.ServiceReference1.ModifyValueRequest();
            inValue.Body = new client.ServiceReference1.ModifyValueRequestBody();
            inValue.Body.Name = Name;
            inValue.Body.Value = Value;
            return ((client.ServiceReference1.WebService1Soap)(this)).ModifyValueAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        client.ServiceReference1.GetElementsResponse client.ServiceReference1.WebService1Soap.GetElements(client.ServiceReference1.GetElementsRequest request) {
            return base.Channel.GetElements(request);
        }
        
        public client.ServiceReference1.ArrayOfString GetElements() {
            client.ServiceReference1.GetElementsRequest inValue = new client.ServiceReference1.GetElementsRequest();
            inValue.Body = new client.ServiceReference1.GetElementsRequestBody();
            client.ServiceReference1.GetElementsResponse retVal = ((client.ServiceReference1.WebService1Soap)(this)).GetElements(inValue);
            return retVal.Body.GetElementsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<client.ServiceReference1.GetElementsResponse> client.ServiceReference1.WebService1Soap.GetElementsAsync(client.ServiceReference1.GetElementsRequest request) {
            return base.Channel.GetElementsAsync(request);
        }
        
        public System.Threading.Tasks.Task<client.ServiceReference1.GetElementsResponse> GetElementsAsync() {
            client.ServiceReference1.GetElementsRequest inValue = new client.ServiceReference1.GetElementsRequest();
            inValue.Body = new client.ServiceReference1.GetElementsRequestBody();
            return ((client.ServiceReference1.WebService1Soap)(this)).GetElementsAsync(inValue);
        }
    }
}
